# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require 'open-uri'
OrderItem.delete_all
CartItem.delete_all
Product.delete_all
User.delete_all

link1 = open('https://toasty-dev.s3-us-west-1.amazonaws.com/eggplant_bag_1.jpg')
link2 = open("https://toasty-dev.s3-us-west-1.amazonaws.com/wall_wooden_map.jpg")
link3 = open("https://toasty-dev.s3-us-west-1.amazonaws.com/ideas.jpg")
link4 = open("https://toasty-dev.s3-us-west-1.amazonaws.com/lui_planter.jpg")
link5 = open("https://toasty-dev.s3-us-west-1.amazonaws.com/succulent_planter_schnauzer.jpg")
link6 = open("https://toasty-dev.s3-us-west-1.amazonaws.com/pastel_botanical.jpg")
link7 = open("https://toasty-dev.s3-us-west-1.amazonaws.com/surfing_pikachu_1.jpg")
link8 = open("https://toasty-dev.s3-us-west-1.amazonaws.com/concrete_planter.jpg")
link9 = open("https://toasty-dev.s3-us-west-1.amazonaws.com/geek_planter.jpg")
link10 = open('https://toasty-dev.s3-us-west-1.amazonaws.com/oil_painting.jpg')
link11 = open('https://toasty-dev.s3-us-west-1.amazonaws.com/toast.jpg')
link12 = open('https://toasty-dev.s3-us-west-1.amazonaws.com/new_seed/book_page_bundle.jpg')
link13 = open('https://toasty-dev.s3-us-west-1.amazonaws.com/new_seed/blue_saphire_ring.jpg')
link14 = open('https://toasty-dev.s3-us-west-1.amazonaws.com/new_seed/corchet_dolls.jpg')
link15 = open('https://toasty-dev.s3-us-west-1.amazonaws.com/new_seed/dog_collar.jpg')
link16 = open('https://toasty-dev.s3-us-west-1.amazonaws.com/new_seed/dog_doormat.jpg')
link17 = open('https://toasty-dev.s3-us-west-1.amazonaws.com/new_seed/blood_moon_kalista_mask.jpg')
link18 = open('https://toasty-dev.s3-us-west-1.amazonaws.com/new_seed/golf_print.jpg')
link19 = open('https://toasty-dev.s3-us-west-1.amazonaws.com/new_seed/handmade_oxford_shoes.jpg')
link20 = open('https://toasty-dev.s3-us-west-1.amazonaws.com/new_seed/beaux_chain.jpg')
link21 = open("https://toasty-dev.s3-us-west-1.amazonaws.com/new_seed/crystal_leggings.jpg")
link22 = open("https://toasty-dev.s3-us-west-1.amazonaws.com/new_seed/fabric_4_ways.jpg")
link23 = open("https://toasty-dev.s3-us-west-1.amazonaws.com/new_seed/fiona_derringer.jpg")
link24 = open("https://toasty-dev.s3-us-west-1.amazonaws.com/new_seed/mens_suit.jpg")
link25 = open("https://toasty-dev.s3-us-west-1.amazonaws.com/new_seed/hex_jewellery_stand.jpg")
link26 = open("https://toasty-dev.s3-us-west-1.amazonaws.com/new_seed/guitar_strap.jpg")
link27 = open("https://toasty-dev.s3-us-west-1.amazonaws.com/new_seed/otter_this_world.jpg")
link28 = open("https://toasty-dev.s3-us-west-1.amazonaws.com/new_seed/out_of_this_world.jpg")
link29 = open("https://toasty-dev.s3-us-west-1.amazonaws.com/new_seed/turquoise_butterfly_earings.jpg")
link30 = open("https://toasty-dev.s3-us-west-1.amazonaws.com/new_seed/onyx_beads.jpg")
link31 = open("https://toasty-dev.s3-us-west-1.amazonaws.com/new_seed/raw_crystal_collection.jpg")
link32 = open("https://toasty-dev.s3-us-west-1.amazonaws.com/new_seed/patchwork_coat.jpg")
link33 = open("https://toasty-dev.s3-us-west-1.amazonaws.com/new_seed/pet_portrait.jpg")
link34 = open("https://toasty-dev.s3-us-west-1.amazonaws.com/new_seed/pet_portrait_mug.jpg")
link35 = open("https://toasty-dev.s3-us-west-1.amazonaws.com/new_seed/tungsten_ring.jpg")
link36 = open("https://toasty-dev.s3-us-west-1.amazonaws.com/new_seed/twisted_cotton.jpg")
link37 = open("https://toasty-dev.s3-us-west-1.amazonaws.com/new_seed/ukulele.jpg")
link38 = open("https://toasty-dev.s3-us-west-1.amazonaws.com/new_seed/wooden_watch.jpg")
link39 = open("https://toasty-dev.s3-us-west-1.amazonaws.com/new_seed/zodiac_glassware.jpg")

user1 = User.create!({name: 'Wilson', email: 'wilson@gmail.com', password: 'password'})
user2 = User.create!({name: "Bob", email: "bob@gmail.com", password: "password"})
user3 = User.create!({name: "May", email: "may@gmail.com", password: "password"})
user4 = User.create!({name: "Ryan", email: "ryan@gmail.com", password: "password"})
user5 = User.create!({name: "Melissa", email: "melissa@gmail.com", password: "password"})
user6 = User.create!({name: "Priscilla", email: "priscilla@gmail.com", password: "password"})
user7 = User.create!({name: "Karissa", email: "karissa@gmail.com", password: "password"})

product1 = Product.create!({name: 'Eggplant Bag', search: 'eggplant bag', description: "Honestly, why wouldn't you want this?", price: 25, artist_id: User.find_by(name: 'Wilson').id, keep: true, category: "Jewelry & Accessories"})
product2 = Product.create!({name: "Wooden Wall Map", search: 'wooden wall map', description: "It's the perfect piece for when you want to see the world but don't have time!", price: 70, artist_id: User.find_by(name: 'Wilson').id, keep: true, category: "Home & Living"})
product3 = Product.create!({name: "Bouquet Painting", search: 'bouquet painting', description: "Great painting for the living room, done on canvas. We deliver all over the world and your order will ship in 2-3 business days. Allow at least 30 days for this item to clear customs.", 
price: 40, artist_id: User.find_by(name: 'Wilson').id, keep: true, category: "Art & Collectibles"})
product4 = Product.create!({name: "Lui Planter - Modern Ceramic Planter", search: "Lui Planter - Modern Ceramic Planter".downcase(), description: "Beige, taupe, and navy color scheme. Great for small plants, such as air plants and succulents. Does not have a drainage hole.", 
price: 13.50, artist_id: User.find_by(name: 'May').id, keep: true, category: "Home & Living"})
product5 = Product.create!({name: "Schnauzer Succulent Planter, Shiba Inu Animal Planter, Corgi Gifts, Sausage Dog Planter, Akita Pug Gift Dachshund Gifts,Siberian Husky Gifts", search: "Schnauzer Succulent Planter, Shiba Inu Animal Planter, Corgi Gifts, Sausage Dog Planter, Akita Pug Gift Dachshund Gifts,Siberian Husky Gifts".downcase(), description: "Yes, you really do get all of them. Ideal for succulents, air plants, and cacti. 
    There is a drainage hole in every planter. Plants are not included.", price: 60, artist_id: User.find_by(name: 'May').id, keep: true, category: "Home & Living"})
product6 = Product.create!({name: "Botanical Print Set", search: "Botanical Print Set".downcase(), description: "Frames are included!", 
price: 40, artist_id: User.find_by(name: "Ryan").id, keep: true, category: "Art & Collectibles"})
product7 = Product.create!({name: "Surfing Pikachu Postcard", search: "Surfing Pikachu Postcard".downcase(), description: "Gotta catch 'em all!", price: 10, artist_id: User.find_by(name: "Wilson").id, keep: true, category: "Art & Collectibles"})
product8 = Product.create!({name: 'HORTUM 10ø | Concrete Planter - Plant Pot - Diameter 10cm (4 inch)', search: "HORTUM 10ø | Concrete Planter - Plant Pot - Diameter 10cm (4 inch)".downcase(), description: "Perfect for your houseplants! There is cork protection at the base to prevent scratches and the surface is sealed with a non-toxic product to make it waterproof.", price: 45, artist_id: User.find_by(name: "Melissa").id, keep: true, category: "Home & Living"})
product9 = Product.create!({name: 'Glasses Succulent Planter', search: "Glasses Succulent Planter".downcase(), description: "Brighten up your room with this super cute succulent planter!", price: 13, artist_id: User.find_by(name: "Melissa").id, keep: true, category: "Home & Living"})
product10 = Product.create!({name: 'Bright Color Brush Strokes Contemporary Artwork Extra Large Square Colorful Modern Abstract Oversize Wall Art Hand Made Canvas Oil Painting', search: 'Bright Color Brush Strokes Contemporary Artwork Extra Large Square Colorful Modern Abstract Oversize Wall Art Hand Made Canvas Oil Painting'.downcase(), description: "I really this painting! Check out 'EARTITALY' on Etsy to find more of their artwork!", price: 700, artist_id: User.find_by(name: "Priscilla").id, keep: true, category: "Art & Collectibles"})
product11 = Product.create!({name: 'Toast', search: "toast", description: "I asked for toast and got this drawn and sent to me within two minutes. Shout-out to Karissa!", price: 999, artist_id: User.find_by(name: "Karissa").id, keep: true, category: "Art & Collectibles"})
product12 = Product.create!({name: 'Vintage Book Page Bundle', search: 'Vintage Book Page Bundle'.downcase(), description: "A beautiful selection of over 150 gorgeous pages from vintage books... to be used for absolutely anything!", price: 10, artist_id: User.find_by(name: "Karissa").id, keep: true, category: "Vintage" })
product13 = Product.create!({name: "CORAL Blue Sapphire Engagement Ring", search: "CORAL Blue Sapphire Engagement Ring".downcase() , description: "This ring is one of the most beloved among our vast signature coral collection, dedicated to the treasury of fascinating colors, sculptural shapes, and diverse forms of life that create this fairy ecosystem.", price: 196, artist_id: User.find_by(name: "Karissa").id, keep: true, category: "Wedding & Party"})
product14 = Product.create!({name: "Custom Crochet Doll", search: "Custom Crochet Doll".downcase(), description: "Allow two weeks to complete!", price: 50, artist_id: User.find_by(name: "Karissa").id, keep: true, category: "Toys & Entertainment" })
product15 = Product.create!({name: "Engraved Gold Buckle Dog Collar", search: "Engraved Gold Buckle Dog Collar".downcase(), description: "With our Laser Engraved Custom Personalized Webbing Dog Collar, the best of both worlds collide to create a super good looking dog collar with all your dog's important info engraved right onto the buckle! No more jingling tag!", price: 45, artist_id: User.find_by(name: "Karissa").id, keep: true, category: "Gifts"})
product16 = Product.create!({name: "Dog Doormat", search: "dog doormat", description: "The struggle is real—warn your guests before they get inside!", price: 54, artist_id: User.find_by(name: "Karissa").id, keep: true, category: "Gifts"})
product17 = Product.create!({name: "Blood Moon Kalista Mask", search: "Blood Moon Kalista Mask".downcase(), description: "Inspired by League of Legends.", price: 208, artist_id: User.find_by(name: "Karissa").id, keep: true, category: "Clothing & Shoes" })
product18 = Product.create!({name: "Vintage Golf Patent Print", search: "Vintage Golf Patent Print".downcase(), description: "You will receive high quality JPG digital files of these listing images each - 8 x 10 inches.", price: 10, artist_id: User.find_by(name: "Karissa").id, keep: true, category: "Vintage"})
product19 = Product.create!({name: "Handmade Oxford Shoes", search: "Handmade Oxford Shoes".downcase(), description: "An amazing oxford shoe made of high-quality leather and zakar fabric with a 1.6cm/0.6'' heel.
This oxford shoe will fit all seasons and can be used as a casual or fancy accessory.", price: 105, artist_id: User.find_by(name: "Karissa").id, keep: true, category: "Clothing & Shoes"})
product20 = Product.create!({name: "Vintage Beaux Chain", search: "Vintage Beaux Chain".downcase(), description: "Elegant brass chain with a great silhouette!", price: 7, artist_id: User.find_by(name: "Karissa").id, keep: true, category: "Vintage"})
product21 = Product.create!({name: "Crystal Leggings", search: "crystal leggings", description: "They’re glow in the dark!", price: 35, artist_id: User.find_by(name: "Karissa").id, keep: true, category: "Clothing & Shoes"})
product22 = Product.create!({name: "Scuba Techno Fabric 4 ways stretch", search: "Scuba Techno Fabric 4 ways stretch".downcase(), description: "Great for pants, dresses, suits, western show clothing, swimsuits , any wearable clothing.. Not water proof, but water repellent.", price: 13, artist_id: User.find_by(name: "Karissa").id, keep: true, category: "Craft Supplies"})
product23 = Product.create!({name: "Fiona's Derringer", search: "Fiona's Derringer".downcase(),description: "Handmade item, non-official replica.", price: 50, artist_id: User.find_by(name: "Karissa").id, keep: true, category: "Toys & Entertainment"})
product24 = Product.create!({name: "Men Suits,Double Breast Suits,Formal Suits for Men, Men Black Suits,2 Piece suits Slim fit Coat Pant", search: "Men Suits,Double Breast Suits,Formal Suits for Men, Men Black Suits,2 Piece suits Slim fit Coat Pant".downcase(), description: "Classic & luxurious Black 2 Piece Suit(Jacket + Pant), hip length Jacket", price: 350, artist_id: User.find_by(name: "Karissa").id, keep: true, category: "Clothing & Shoes" })
product25 = Product.create!({name: "Personalized Gents Hex Jewelry Stand", search: "Personalized Gents Hex Jewelry Stand".downcase(), description: "A stylishly individual and contemporary sculptured hex personalized jewelry stand designed and hand crafted from solid American Black walnut or Oak with real leather detail in contrasting grey.", price: 50,artist_id: User.find_by(name: "Karissa").id, keep: true, category: "Wedding & Party" })
product26 = Product.create!({name: '"Zephyr" Guitar Strap', search: '"Zephyr" Guitar Strap'.downcase(), description: "Simple, beautiful and highly practical, a guitar strap that will last a lifetime.", price: 97, artist_id: User.find_by(name: "Karissa").id, keep: true, category: "Toys & Entertainment"})
product27 = Product.create!({name: "Otter This World", search: "otter this world", description: "Ha. Get it?", price: 3, artist_id: User.find_by(name: 'Karissa').id, keep: true, category: "Jewelry & Accessories" })
product28 = Product.create!({name: "Out of this World - Galaxy - Cotton Fabric", search: "Out of this World - Galaxy - Cotton Fabric".downcase(), description: "Colors include shades of blue, green, purple and white.", price: 3, artist_id: User.find_by(name: "Karissa").id, keep: true, category: "Craft Supplies"})
product29 = Product.create!({name: "Turquoise Butterfly Earrings", search: "Turquoise Butterfly Earrings".downcase(), description: "Alright these are pretty cool.", price: 30, artist_id: User.find_by(name: 'Karissa').id, keep: true, category: "Jewelry & Accessories"})
product30 = Product.create!({name: "Natural Matte Black Onyx Beads", search: "Natural Matte Black Onyx Beads".downcase(), description: "High quality black onyx beads.", price: 2, artist_id: User.find_by(name: 'Karissa').id, keep: true, category: "Craft Supplies"})
product31 = Product.create!({name: "Intuitively Chosen Raw Crystal Set", search: "Intuitively Chosen Raw Crystal Set".downcase(), description: "Natural raw crystal set intuitively chosen by a certified crystal and vibrational healer, special just for you and your unique journey!", price: 25, artist_id: User.find_by(name: "Karissa").id, keep: true, category: "Vintage"})
product32 = Product.create!({name: "Patchwork Coat", search: "patchwork coat", description: "Hand knit/crocheted granny square afghan coat- jacket with the optional hood design for women. This long crochet coat has an oversized and open front pattern.", price: 200, artist_id: User.find_by(name: "Karissa").id, keep: true, category: "Clothing & Shoes"})
product33 = Product.create!({name: "Personalized Embroidered Pet Portrait", search: "Personalized Embroidered Pet Portrait".downcase(), description: "This custom pet portrait makes a great addition to any room in your home and an unforgettable gift for any pet lover!", price: 38, artist_id: User.find_by(name: "Karissa").id, keep: true, category: "Gifts" })
product34 = Product.create!({name: "Carved Pet Portrait Mug", search: "Carved Pet Portrait Mug".downcase(), description: "A gift for someone who loves their pet as much as they love their coffee.", price: 60, artist_id: User.find_by(name: "Karissa").id, keep: true, category: "Gifts" })
product35 = Product.create!({name: "Tungsten Meteorite Ring",search: "tungsten meteorite ring", description: "Meteorite rings are extremely popular right now & perfect for those seeking a one of a kind design. It looks even more stunning in person with its polished tungsten band with crystalline meteorite inlay. No two inlays are the same making this exclusive to you!", price: 98, artist_id: User.find_by(name: "Karissa").id, keep: true, category: "Wedding & Party"})
product36 = Product.create!({name: "Twisted Cotton Cord", search: "twisted cotton cord", description: "Finest quality cotton cord, perfect for any macrame project such as plant hangers, wall hangings, curtains, bags etc.", price: 35, artist_id: User.find_by(name: "Karissa").id, keep: true, category: "Craft Supplies"})
product37 = Product.create!({name: "Crazy Cat Lady Ukulele", search: "crazy cat lady ukulele", description: "'Crazy Cat Lady' Ukulele, perfect for all cat loving ukulele players! Original, hand illustrated cats together on a ukulele guaranteed to impress :)", price: 113, artist_id: User.find_by(name: "Karissa").id, keep: true, category: "Toys & Entertainment"})
product38 = Product.create!({name: "Wooden Watch", search: "wooden watch", description: "Have you been looking for a truly unique timepiece that can separate itself from the rest? Whether be for yourself, for your partner, or for your friends and families?", price: 90, artist_id: User.find_by(name: "Karissa").id, keep: true, category: "Jewelry & Accessories"})
product39 = Product.create!({name: "Zodiac Constellation Astrology Glassware", search: "Zodiac Constellation Astrology Glassware".downcase(), description: "What's your sign? These glasses celebrate your spot in the celestial sphere! This special-edition series of cooler glasses features all 12 constellations of the zodiac to cover your astrological needs.", price: 25, artist_id: User.find_by(name: "Karissa").id, keep: true, category: "Wedding & Party"})

puts(product1)
puts(product2.name)
puts(product2.photo)
puts(product2.photo.attached?)
# console.log(product2)
# product1.photo.attach(io: link1, filename: 'eggplant.jpg')
# product2.photo.attach(io: link2, filename: 'wooden_wall_map.jpg')
# puts(product2.photo.attached?)
# product3.photo.attach(io: link3, filename: 'idea.jpg')
# product4.photo.attach(io: link4, filename: 'lui_planter.jpg')
# product5.photo.attach(io: link5, filename: 'dog_planters.jpg')
# product6.photo.attach(io: link6, filename: 'pastel_botanical.jpg')
# product7.photo.attach(io: link7, filename: 'surfing_pikachu_1.jpg')
# product8.photo.attach(io: link8, filename: 'concrete_planter.jpg')
# product9.photo.attach(io: link9, filename: 'geek_planter.jpg')
# product10.photo.attach(io: link10, filename: 'oil_painting.jpg')
# product11.photo.attach(io: link11, filename: 'toast.jpg')
# product12.photo.attach(io: link12, filename: 'book_bundle.jpg')
# product13.photo.attach(io: link13, filename: 'sapphire_ring.jpg')
# product14.photo.attach(io: link14, filename: 'crochet_dolls.jpg')
# product15.photo.attach(io: link15, filename: 'dog_collar.jpg')
# product16.photo.attach(io: link16, filename: 'doormat.jpg')
# product17.photo.attach(io: link17, filename: "kalista.jpg")
# product18.photo.attach(io: link18, filename: "golf.jpg")
# product19.photo.attach(io: link19, filename: "oxford.jpg")
# product20.photo.attach(io: link20, filename: "chain.jpg")
# product21.photo.attach(io: link21, filename: "legging.jpg")
# product22.photo.attach(io: link22, filename: "4_ways.jpg")
# product23.photo.attach(io: link23, filename: "fiona.jpg")
# product24.photo.attach(io: link24, filename: "men_suit.jpg")
# product25.photo.attach(io: link25, filename: "hex.jpg")
# product26.photo.attach(io: link26, filename: "guitar.jpg")
# product27.photo.attach(io: link27, filename: "otter.jpg")
# product28.photo.attach(io: link28, filename: "galaxy.jpg")
# product29.photo.attach(io: link29, filename: "galaxy_craft.jpg")
# product30.photo.attach(io: link30, filename: "onyx.jpg")
# product31.photo.attach(io: link31, filename: "crystal_set.jpg")
# product32.photo.attach(io: link32, filename: "patchwork.jpg")
# product33.photo.attach(io: link33, filename: "embroidered_pet.jpg")
# product34.photo.attach(io: link34, filename: "mug.jpg")
# product35.photo.attach(io: link35, filename: "tungsten.jpg")
# product36.photo.attach(io: link36, filename: "twisted.jpg")
# product37.photo.attach(io: link37, filename: "ukulele.jpg")
# product38.photo.attach(io: link38, filename: "watch.jpg")
# product39.photo.attach(io: link39, filename: "zodiac.jpg")
